---
driver:
  name: vagrant


provisioner:
  name: nodes
  require_chef_omnibus: 12.18.31
  # chef_omnibus_url: file:///chef-pkgs/install.sh
  # environments_path: test/environments
  data_bags_path: test/integration/data_bags
  # client_rb:
  #   environment: kitchen

verifier:
  name: inspec

platforms:
  - name: centos-7.2

suites:
  - name: fabio
    driver:
        vm_hostname: fabio
    run_list:
      - recipe[apt]
      - recipe[yum]
      - recipe[didata-fabio::default]
      - recipe[didata-fabio::binary]
      - recipe[didata-fabio::configure]
    attributes:
      chef-vault:
        databag_fallback: true