---
driver:
  name: docker
  binary: docker
  # socket: tcp://docker-host:2375
  use_sudo: false
  provision_command:
    - curl -L https://www.chef.io/chef/install.sh | bash -s -- -v 12.18.31
  privileged: true
  publish_all: true
  run_options:
    net: bridge


provisioner:
  name: chef_solo
  data_bags_path: test/integration/data_bags

platforms:
  - name: centos-7.2
  # - name: ubuntu
  # - name: debian

suites:
  - name: fabio
    run_list:
      - recipe[apt]
      - recipe[yum]
      - recipe[didata-fabio::default]
      - recipe[didata-fabio::binary]
      - recipe[didata-fabio::configure]
    attributes:
      chef-vault:
        databag_fallback: true


